### ISSUE TITLE
Cannot read property 'apiCall' of undefined

### ISSUE THREAD

**Issue by Spankyed** [pthoresen/conversation-extension-framework#19]
Started getting this error couple days ago. 

`
TypeError: Cannot read property 'apiCall' of undefined
    at Object.processMessage (C:\Users\Angel\desktop\vishval\src\process-handler\process.js:60:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4032) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'apiCa
ll' of undefined
(node:4032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are n
ot handled will terminate the Node.js process with a non-zero exit code.
req undefined
TypeError: Cannot read property 'apiCall' of undefined
    at Object.processMessage (C:\Users\Angel\desktop\vishval\src\process-handler\process.js:60:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4032) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'apiCa
ll' of undefined
`

Any help?

**Comment by Spankyed** [comment]
You will get this error if you don't have workspace and conversation credentials configured correctly. Learn from my mistakes please.

**Comment by pthoresen** [comment]
Thank you, I'll try to make it clearer in future releases. When I have a chance, I want to tighten some things up and remove functionality that has since been added to the base WCS product.

**Comment by Spankyed** [comment]
Word. Glad to hear you are still maintaining it.
