### ISSUE TITLE
Now way to reset context variables via API or Conversation notation

### ISSUE THREAD

**Issue by wernervz** [pthoresen/conversation-extension-framework#8]
Hi Paul,

I'm trying to reset some context vars when the user says reset or thanks.  But the framework maintains the context even if I make the context variable values null in the conversation.

Werner

**Comment by pthoresen** [comment]
@wernervz Do you mean that you set the context['field'] to null in your Conversation node and that does not persist? So the next time you send a message you see context['field'] with the previous value?

I think I'll have to add a check for null fields and delete them if that's the case.

In the meantime, as a workaround, you probably could define a function that will reset your values and just call it like any API call

**Comment by pthoresen** [comment]
context can be modified as needed via API call function. 

Closing as not an issue.
