### ISSUE TITLE
When to use this package? Feature req

### ISSUE THREAD

**Issue by adamgins** [pthoresen/conversation-extension-framework#9]
I know this is probably more of a Stackoverflow question http://stackoverflow.com/questions/43532612/wtason-conversation-api-when-to-use-which-package...  any chance you can include a FAQ in the documentation, pls?

**Comment by pthoresen** [comment]
Thanks for the feedback. I'll push an update to the README to address this shortly.

**Comment by pthoresen** [comment]
addressed in #10
